import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
test('legacy Telegram offset normal migration preserves unknown data; foreign chat and missing credentials send nothing',t=>{
  const root=mkdtempSync(join(tmpdir(),'batch-telegram-migration-'));
  t.after(()=>rmSync(root,{recursive:true,force:true}));
  const state=join(root,'state');mkdirSync(state);
  writeFileSync(join(state,'telegram-token.txt'),'synthetic-unusable-token');
  writeFileSync(join(state,'telegram-chat.json'),'\ufeff{"chat_id":1}');
  writeFileSync(join(state,'telegram-offset.json'),'\ufeff{"schema":"night-batch-ops/offset/1","offset":7,"preserved":true}');
  const source=`import assert from 'node:assert/strict';
    import {readFileSync,unlinkSync} from 'node:fs';
    import {join} from 'node:path';
    import {pollOnce} from ${JSON.stringify(new URL('./telegram-commands.mjs',import.meta.url).href)};
    let sends=0;
    const deps={getUpdates:async(_token,offset)=>{assert.equal(offset,7);return [{update_id:7,message:{chat:{id:999},text:'/status'}}]},now:()=>Date.now(),send:async()=>{sends++}};
    await pollOnce(deps);
    const record=JSON.parse(readFileSync(join(process.env.AUTO_BATCH_STATE_DIR,'telegram-offset.json'),'utf8'));
    assert.deepEqual(record,{schema:'batch-24-multiag/offset/1',offset:8,preserved:true});
    assert.equal(sends,0);
    unlinkSync(join(process.env.AUTO_BATCH_STATE_DIR,'telegram-chat.json'));
    assert.deepEqual(await pollOnce(deps),{handled:0});assert.equal(sends,0);
    console.log('migration verified');`;
  const env={...process.env,AUTO_BATCH_STATE_DIR:state,HOME:root,USERPROFILE:root};delete env.NODE_TEST_CONTEXT;
  const r=spawnSync(process.execPath,['--input-type=module','-e',source],{cwd:root,env,encoding:'utf8',timeout:30000,windowsHide:true});
  assert.equal(r.status,0,r.stdout+r.stderr);assert.match(r.stdout,/migration verified/);
});
